let data = {
    prizeList: [15, 13, 5, 3],
    // prizeList: [0,0,0,1],
    prizeLeft: 0,
    prize: [],
    prizename: ["25K", "50K", "75K", "100K"],
    history: [],
    lottery: [
        { id: 1, name: "Anthony" },
        { id: 2, name: "Anthony" },
        { id: 3, name: "Talia" },
        { id: 4, name: "Jesnat" },
        { id: 5, name: "Dewi" },
        { id: 6, name: "Frederic" },
        { id: 7, name: "kesuma" },
        { id: 8, name: "kesuma" },
        { id: 9, name: "robert" },
        { id: 10, name: "kesuma" },
        { id: 11, name: "Dewi" },
        { id: 12, name: "kesuma" },
        { id: 13, name: "Vanvit" },
        { id: 14, name: "robert" },
        { id: 15, name: "Ilone" },
        { id: 16, name: "Rafa" },
        { id: 17, name: "Ilone" },
        { id: 18, name: "Rafa" },
        { id: 19, name: "robert" },
        { id: 20, name: "Levandio" },
        { id: 21, name: "Talia" },
        { id: 22, name: "Rafa" },
        { id: 23, name: "Noel" },
        { id: 24, name: "Noel" },
        { id: 25, name: "Rafa" },
        { id: 26, name: "Cindy" },
        { id: 27, name: "Dewi" },
        { id: 28, name: "BV" },
        { id: 29, name: "Kevin" },
        { id: 30, name: "Pranata" },
        { id: 31, name: "Kevin" },
        { id: 32, name: "Pranata" },
        { id: 33, name: "Michael C" },
        { id: 34, name: "Vanvit" },
        { id: 35, name: "robert" },
        { id: 36, name: "VDR" },
        { id: 38, name: "Hansen" },
        { id: 39, name: "Levandio" },
        { id: 40, name: "Kelvin" },
        { id: 42, name: "Jose" },
        { id: 44, name: "Michael C" },
        { id: 45, name: "Ellaine" },
        { id: 46, name: "NaiFang" },
        { id: 47, name: "Jesnat" },
        { id: 48, name: "PS" },
        { id: 49, name: "PS" },
        { id: 50, name: "Gracia" },
        { id: 51, name: "Jemong" },
        { id: 52, name: "Ivander" },
        { id: 55, name: "NaiFang" },
        { id: 56, name: "Gracia" },
        { id: 57, name: "NaiFang" },
        { id: 58, name: "Vanvit" },
        { id: 59, name: "Vanvit" },
        { id: 60, name: "Cindy" },
        { id: 61, name: "Theo" },
        { id: 63, name: "Jemong" },
        { id: 64, name: "Ivander" },
        { id: 65, name: "BV" },
        { id: 66, name: "Ellaine" },
        { id: 67, name: "Eveline" },
        { id: 68, name: "Frederic" },
        { id: 69, name: "Kelvin" },
        { id: 70, name: "Theo" },
        { id: 71, name: "Jose" },
        { id: 73, name: "Eveline" },
        { id: 75, name: "NaiFang" },
        { id: 77, name: "Dewi" },
        { id: 79, name: "VDR" },
        { id: 80, name: "Hansen" },
    ],
};


let log = {
    history : [],
    shuffleQueue : []
}